### ISSUE TITLE
Unable to combine custom neuron and neurite (both having BiologyModules)

### ISSUE THREAD

**Issue by jojofranz** [jojofranz/combine_modules#2]
I am unable to combine custom neuron (MyCell) and neurite (MyNeurite) when both are having BiologyModules that are not the NullBiologyModule.

Note that I do not intend to divide cells with attached neurites. Division is intended to occur first and the division module is removed from MyCell before the addition of neurites.

**Terminal output:**
```shell
Build

Run combine_modules 
Info: Initialize new simulation using BioDynaMo v0.1.0-152-ge3d39e63
Fatal in <Variant>: You called the constructor with a type that is not in Types...
aborting

Thread 4 (Thread 0x7fd8a84f9700 (LWP 16668)):
#0  0x00007fd8cd9d9f1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007fd8cd9d7938 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007fd8ceefa6db in start_thread (arg=0x7fd8a84f9700) at pthread_create.c:463
#3  0x00007fd8cd4d988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fd8a8cfa700 (LWP 16667)):
#0  0x00007fd8cd9d9f1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007fd8cd9d7938 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007fd8ceefa6db in start_thread (arg=0x7fd8a8cfa700) at pthread_create.c:463
#3  0x00007fd8cd4d988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fd8a94fb700 (LWP 16666)):
#0  0x00007fd8cd9d9f1e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007fd8cd9d7938 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007fd8ceefa6db in start_thread (arg=0x7fd8a94fb700) at pthread_create.c:463
#3  0x00007fd8cd4d988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fd8d14d5b80 (LWP 16651)):
#0  0x00007fd8cd49c6c2 in __GI___waitpid (pid=16671, stat_loc=stat_loc
entry=0x7ffd686a6c28, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007fd8cd407067 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:149
#2  0x00007fd8d07e93e7 in TUnixSystem::StackTrace() () from /home/johannes/.bdm/third_party/root/lib/libCore.so
#3  0x00007fd8d06eaf80 in DefaultErrorHandler(int, bool, char const*, char const*) () from /home/johannes/.bdm/third_party/root/lib/libCore.so
#4  0x00007fd8d06ea912 in ErrorHandler () from /home/johannes/.bdm/third_party/root/lib/libCore.so
#5  0x00007fd8d06eae0f in Fatal(char const*, char const*, ...) () from /home/johannes/.bdm/third_party/root/lib/libCore.so
#6  0x000055e96f0e202b in void std::vector<bdm::Variant<bdm::ApicalElongationBM, bdm::BasalElongationBM>, std::allocator<bdm::Variant<bdm::ApicalElongationBM, bdm::BasalElongationBM> > >::_M_realloc_insert<bdm::GrowDivide>(__gnu_cxx::__normal_iterator<bdm::Variant<bdm::ApicalElongationBM, bdm::BasalElongationBM>*, std::vector<bdm::Variant<bdm::ApicalElongationBM, bdm::BasalElongationBM>, std::allocator<bdm::Variant<bdm::ApicalElongationBM, bdm::BasalElongationBM> > > >, bdm::GrowDivide&&) ()
#7  0x000055e96f0e8652 in bdm::experimental::neuroscience::NeuronSomaExt<bdm::CompileTimeParam<bdm::SoaRef>, bdm::Capsule<bdm::MyCellExt> >::ExtendNewNeurite(double, double, double) ()
#8  0x000055e96f0e8b06 in bdm::Simulate(int, char const**)::{lambda(bdm::MyCellExt<bdm::CompileTimeParam<bdm::Scalar>, bdm::Capsule<bdm::MyCellExt> >)#2}::operator()(bdm::MyCellExt<bdm::CompileTimeParam<bdm::Scalar>, bdm::Capsule<bdm::MyCellExt> >) const ()
#9  0x000055e96f0ee52b in bdm::Simulate(int, char const**) ()
#10 0x00007fd8cd3d9b97 in __libc_start_main (main=0x55e96f070290 <main>, argc=2, argv=0x7ffd686a9e98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd686a9e88) at ../csu/libc-start.c:310
#11 0x000055e96f0702ca in _start ()
```

On a side note:
Even when I use only the NullBiologyModule for MyCell, I get an error. (This might be a different issue though, as a similar simulation did finish.)

**Terminal output:**
```
Build

Run combine_modules 
Info: Initialize new simulation using BioDynaMo v0.1.0-152-ge3d39e63
terminate called without an active exception

Error during execution of ./build/combine_modules
```

**Comment by jojofranz** [comment]
Solved by Lukas 'Refactor simulation to dynamic biodynamo version' pull request.
